language: java

jdk:
  - openjdk7

branches:
  only:
    - travis-testing

script:
  - mvn install

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
