language: java

jdk:
  - openjdk7

branches:
  only:
    - travis-testing

script:
  - mvn install
  - ls -lR /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/dependency/cmake
  - /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/dependency/cmake/bin/cmake --version
  - mvn help:active-profiles
  - ls -la /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
