language: java

jdk:
  - openjdk7

branches:
  only:
    - travis-testing

# CMake is 32 bit and Travis VMs are 64 bit; install 32 bit libs before testing
script:
  - sudo apt-get install gcc-multilib
  - mvn install

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
