language: java

jdk:
  - openjdk7

branches:
  only:
    - travis-testing

script:
  - mvn install
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/dependency/cmake/bin/cmake
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/dependency/cmake/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/dependency/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/target/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/dashboard-test/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/test-classes/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/target/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/cmake-maven-plugin/
  - ls -l /home/travis/build/ksclarke/cmake-maven-project/
  - ls -l /home/travis/build/ksclarke/
  - ls -l /home/travis/build/
  - ls -l /home/travis/
  - ls -l /home/

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
